# Use an official Python runtime as a parent image
FROM python:3.12-slim-bookworm

# Set the working directory in the container
WORKDIR /contract-indexer

# Copy the current directory contents into the container
COPY . /contract-indexer

# Install the required Python packages
RUN pip install --no-cache-dir web3 prometheus-client

# Expose the port that the Prometheus server is running on
EXPOSE 8000

# Run the indexer script
CMD ["python", "indexer.py"]
